version: "3.9"

services:
  db:
    image: postgres:15
    container_name: financeiro_db
    restart: always
    environment:
      POSTGRES_DB: financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: financeiro_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3333
      CORS_ORIGIN: "*"
    ports:
      - "3333:3333"

  etl:
    build: ./etl-snk
    container_name: financeiro_etl
    restart: always
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production

  web:
    build: ./web
    container_name: financeiro_front
    restart: always
    ports:
      - "8080:80"

volumes:
  pgdata:
