services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env.prod
    expose:
      - "3333"
    networks:
      - app_net

  etl-snk:
    build:
      context: ./etl-snk
      dockerfile: Dockerfile
    container_name: etl-snk
    env_file:
      - .env.prod
    networks:
      - app_net

  app-client:
    build:
      context: ./web/app-client
      dockerfile: Dockerfile
    container_name: app-client
    expose:
      - "80"
    networks:
      - app_net

  app-history-client:
    build:
      context: ./web/app-history-client
      dockerfile: Dockerfile
    container_name: app-history-client
    expose:
      - "80"
    networks:
      - app_net

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - app-client
      - app-history-client
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
